### ISSUE TITLE
Toast Messages need to be displayed for submission of 'Individual Background' and 'Workout Outline'

### ISSUE THREAD

**Issue by Collin-Potter** [MatthewCookUNR/DJ-Fit#6]
Noticed that I wasn't sure if my information was saved. Simple popups should suffice to improve user satisfaction.

**Comment by Collin-Potter** [comment]
I'll be able to take care of this. Just wanted to throw it out there as something to do

**Comment by MatthewCooksCode** [comment]
That is definitely sensible. I will work on doing so as soon as I get a chance if you haven't done so already.

**Comment by Collin-Potter** [comment]
I have made a pull request for the fix

**Comment by Collin-Potter** [comment]
It's a simple fix, but it works. I don't think it should take that much stressing since toast messages already exist.

**Comment by Collin-Potter** [comment]
Just reopening for visibility until PR is merged
